export const lignes = [
  { gareA: "Mulhouse", gareB: "Mulhouse Dornach", longueur: 3.9, type: "classique", vitesse_max: 80, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Colmar", gareB: "Sélestat", longueur: 23.4, type: "classique", vitesse_max: 160, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Sélestat", gareB: "Strasbourg", longueur: 48.5, type: "classique", vitesse_max: 160, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Mulhouse Dornach", gareB: "Lutterbach", longueur: 3.7, type: "classique", vitesse_max: 160, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Lutterbach", gareB: "Staffelfelden", longueur: 8, type: "classique", vitesse_max: 200, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Staffelfelden", gareB: "Bollwiller", longueur: 3.3, type: "classique", vitesse_max: 200, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Bollwiller", gareB: "Raedersheim", longueur: 4, type: "classique", vitesse_max: 200, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Raedersheim", gareB: "Merxheim", longueur: 3.6, type: "classique", vitesse_max: 200, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Merxheim", gareB: "Rouffach", longueur: 5.4, type: "classique", vitesse_max: 200, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Rouffach", gareB: "Herrlisheim-Près-Colmar", longueur: 6.4, type: "classique", vitesse_max: 200, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Herrlisheim-Près-Colmar", gareB: "Colmar", longueur: 6.9, type: "classique", vitesse_max: 160, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Mulhouse", gareB: "Habsheim", longueur: 12, type: "classique", vitesse_max: 140, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Habsheim", gareB: "Sierentz", longueur: 10.5, type: "classique", vitesse_max: 160, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Sierentz", gareB: "Bartenheim", longueur: 3.9, type: "classique", vitesse_max: 160, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Bartenheim", gareB: "Saint-Louis la Chaussée", longueur: 5.6, type: "classique", vitesse_max: 160, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Saint-Louis la Chaussée", gareB: "Saint-Louis", longueur: 3.5, type: "classique", vitesse_max: 160, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Saint-Louis", gareB: "Bâle Saint-Jean", longueur: 2.9, type: "classique", vitesse_max: 140, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Bâle Saint-Jean", gareB: "Basel SBB", longueur: 4.2, type: "classique", vitesse_max: 140, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Bartenheim", gareB: "Aéroport Bâle-Mulhouse Terminal", longueur: 6.6, type: "classique", vitesse_max: 140, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Aéroport Bâle-Mulhouse Terminal", gareB: "Saint-Louis", longueur: 3.4, type: "classique", vitesse_max: 140, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Mulhouse", gareB: "Flaxlanden", longueur: 6.7, type: "classique", vitesse_max: 140, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Flaxlanden", gareB: "Illfurth", longueur: 4.8, type: "classique", vitesse_max: 140, electrification: "25kV CA", signalisation: "KVB" },
  { gareA: "Illfurth", gareB: "Altkirch", longueur: 6.8, type: "classique", vitesse_max: 140, electrification: "25kV CA", signalisation: "KVB" },
  { gareA: "Altkirch", gareB: "Dannemarie", longueur: 13.8, type: "classique", vitesse_max: 160, electrification: "25kV CA", signalisation: "KVB" },
  { gareA: "Dannemarie", gareB: "Montreux-Vieux", longueur: 11.5, type: "classique", vitesse_max: 160, electrification: "25kV CA", signalisation: "KVB" },
  { gareA: "Montreux-Vieux", gareB: "Petit-Croix", longueur: 3.6, type: "classique", vitesse_max: 160, electrification: "25kV CA", signalisation: "KVB" },
  { gareA: "Petit-Croix", gareB: "Belfort-Ville", longueur: 16.1, type: "classique", vitesse_max: 140, electrification: "25kV CA", signalisation: "KVB" }
];