export const lignes = [
  { gareA: "Mulhouse", gareB: "Mulhouse Dornach", longueur: 3.9, type: "classique", vitesse_max: 80, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Mulhouse Dornach", gareB: "Lutterbach", longueur: 3.7, type: "classique", vitesse_max: 160, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Lutterbach", gareB: "Staffelfelden", longueur: 8, type: "classique", vitesse_max: 200, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Staffelfelden", gareB: "Bollwiller", longueur: 3.3, type: "classique", vitesse_max: 200, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Bollwiller", gareB: "Raedersheim", longueur: 4, type: "classique", vitesse_max: 200, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Raedersheim", gareB: "Merxheim", longueur: 3.6, type: "classique", vitesse_max: 200, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Merxheim", gareB: "Rouffach", longueur: 5.4, type: "classique", vitesse_max: 200, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Rouffach", gareB: "Herrlisheim-Près-Colmar", longueur: 6.4, type: "classique", vitesse_max: 200, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Herrlisheim-Près-Colmar", gareB: "Colmar", longueur: 6.9, type: "classique", vitesse_max: 160, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Mulhouse", gareB: "_CourbeMulhouseNord", longueur: 6, type: "classique", vitesse_max: 140, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "_CourbeMulhouseNord", gareB: "Habsheim", longueur: 6, type: "classique", vitesse_max: 140, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Habsheim", gareB: "Sierentz", longueur: 10.5, type: "classique", vitesse_max: 160, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Sierentz", gareB: "Bartenheim", longueur: 3.9, type: "classique", vitesse_max: 160, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Bartenheim", gareB: "Saint-Louis la Chaussée", longueur: 5.6, type: "classique", vitesse_max: 160, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Saint-Louis la Chaussée", gareB: "Saint-Louis", longueur: 3.5, type: "classique", vitesse_max: 160, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Saint-Louis", gareB: "Bâle Saint-Jean", longueur: 2.9, type: "classique", vitesse_max: 140, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Bâle Saint-Jean", gareB: "Basel SBB", longueur: 4.2, type: "classique", vitesse_max: 140, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Bartenheim", gareB: "Aéroport Bâle-Mulhouse Terminal", longueur: 6.6, type: "tunnel", vitesse_max: 140, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Aéroport Bâle-Mulhouse Terminal", gareB: "Saint-Louis", longueur: 3.4, type: "tunnel", vitesse_max: 140, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Mulhouse", gareB: "Flaxlanden", longueur: 6.7, type: "classique", vitesse_max: 140, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Flaxlanden", gareB: "Illfurth", longueur: 4.8, type: "classique", vitesse_max: 140, electrification: "25kV CA", signalisation: "KVB" },
  { gareA: "Illfurth", gareB: "Altkirch", longueur: 6.8, type: "classique", vitesse_max: 140, electrification: "25kV CA", signalisation: "KVB" },
  { gareA: "Altkirch", gareB: "Dannemarie", longueur: 13.8, type: "classique", vitesse_max: 160, electrification: "25kV CA", signalisation: "KVB" },
  { gareA: "Dannemarie", gareB: "Montreux-Vieux", longueur: 11.5, type: "classique", vitesse_max: 160, electrification: "25kV CA", signalisation: "KVB" },
  { gareA: "Montreux-Vieux", gareB: "Petit-Croix", longueur: 3.6, type: "classique", vitesse_max: 160, electrification: "25kV CA", signalisation: "KVB" },
  { gareA: "Petit-Croix", gareB: "Belfort-Ville", longueur: 16.1, type: "classique", vitesse_max: 140, electrification: "25kV CA", signalisation: "KVB" },
  { gareA: "Lutterbach", gareB: "Graffenwald", longueur: 6.3, type: "classique", vitesse_max: 120, electrification: "25kV CA", signalisation: "KVB" },
  { gareA: "Graffenwald", gareB: "Cernay", longueur: 6.1, type: "classique", vitesse_max: 120, electrification: "25kV CA", signalisation: "KVB" },
  { gareA: "Cernay", gareB: "Thann Gare", longueur: 7.6, type: "classique", vitesse_max: 80, electrification: "25kV CA", signalisation: "KVB" },
  { gareA: "Thann Gare", gareB: "Bitschwiller-lès-Thann", longueur: 3.8, type: "classique", vitesse_max: 80, electrification: "diesel", signalisation: "KVB" },
  { gareA: "Bitschwiller-lès-Thann", gareB: "Willer-sur-Thur", longueur: 2, type: "classique", vitesse_max: 80, electrification: "diesel", signalisation: "KVB" },
  { gareA: "Willer-sur-Thur", gareB: "Saint-Amarin", longueur: 5.7, type: "classique", vitesse_max: 80, electrification: "diesel", signalisation: "KVB" },
  { gareA: "Saint-Amarin", gareB: "Wesserling", longueur: 3.9, type: "classique", vitesse_max: 80, electrification: "diesel", signalisation: "KVB" },
  { gareA: "Wesserling", gareB: "Oderen", longueur: 3.5, type: "classique", vitesse_max: 80, electrification: "diesel", signalisation: "KVB" },
  { gareA: "Oderen", gareB: "Kruth", longueur: 1.6, type: "classique", vitesse_max: 60, electrification: "diesel", signalisation: "KVB" },
  { gareA: "Mulhouse", gareB: "Bantzenheim", longueur: 19.5, type: "classique", vitesse_max: 90, electrification: "25kV CA", signalisation: "KVB" },
  { gareA: "Bantzenheim", gareB: "Neuenburg (Baden)", longueur: 6.5, type: "classique", vitesse_max: 90, electrification: "15kV CA", signalisation: "PZB" },
  { gareA: "Neuenburg (Baden)", gareB: "Muellheim", longueur: 4.4, type: "classique", vitesse_max: 80, electrification: "15kV CA", signalisation: "PZB" },
  { gareA: "Colmar", gareB: "_ColSél-Ostheim", longueur: 10.4, type: "classique", vitesse_max: 200, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "_ColSél-Ostheim", gareB: "Sélestat", longueur: 13.9, type: "classique", vitesse_max: 200, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Sélestat", gareB: "Ebersheim", longueur: 8, type: "classique", vitesse_max: 200, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Ebersheim", gareB: "Kogenheim", longueur: 5.5, type: "classique", vitesse_max: 200, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Kogenheim", gareB: "Benfeld", longueur: 6.7, type: "classique", vitesse_max: 200, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Benfeld", gareB: "Erstein", longueur: 8.2, type: "classique", vitesse_max: 200, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Erstein", gareB: "Fegersheim - Lipsheim", longueur: 8.4, type: "classique", vitesse_max: 160, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Fegersheim - Lipsheim", gareB: "Graffenstaden", longueur: 5, type: "classique", vitesse_max: 160, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Graffenstaden", gareB: "_courbeStrasSud", longueur: 4.8, type: "classique", vitesse_max: 140, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "_courbeStrasSud", gareB: "Strasbourg", longueur: 3.3, type: "classique", vitesse_max: 90, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Metzeral", gareB: "Muhlbach-sur-Munster", longueur: 2.2, type: "classique", vitesse_max: 80, electrification: "diesel", signalisation: "KVB" },
  { gareA: "Muhlbach-sur-Munster", gareB: "Munster", longueur: 5.4, type: "classique", vitesse_max: 80, electrification: "diesel", signalisation: "KVB" },
  { gareA: "Munster", gareB: "Wihr-au-Val - Soultzbach", longueur: 8.4, type: "classique", vitesse_max: 90, electrification: "diesel", signalisation: "KVB" },
  { gareA: "Wihr-au-Val - Soultzbach", gareB: "Turckheim", longueur: 9.2, type: "classique", vitesse_max: 90, electrification: "diesel", signalisation: "KVB" },
  { gareA: "Turckheim", gareB: "Logelbach", longueur: 4.8, type: "classique", vitesse_max: 90, electrification: "diesel", signalisation: "KVB" },
  { gareA: "Logelbach", gareB: "Colmar", longueur: 3.5, type: "classique", vitesse_max: 90, electrification: "diesel", signalisation: "KVB" },
  { gareA: "Molsheim", gareB: "Duttlenheim", longueur: 7.4, type: "classique", vitesse_max: 100, electrification: "diesel", signalisation: "KVB" },
  { gareA: "_courbeStrasSud", gareB: "Lingolsheim", longueur: 3.6, type: "classique", vitesse_max: 100, electrification: "diesel", signalisation: "KVB" },
  { gareA: "Lingolsheim", gareB: "Entzheim-Aéroport", longueur: 5.7, type: "classique", vitesse_max: 100, electrification: "diesel", signalisation: "KVB" },
  { gareA: "Entzheim-Aéroport", gareB: "Duttlenheim", longueur: 6.9, type: "classique", vitesse_max: 100, electrification: "diesel", signalisation: "KVB" },
  { gareA: "Sélestat", gareB: "Scherwiller", longueur: 3.3, type: "classique", vitesse_max: 80, electrification: "diesel", signalisation: "KVB" },
  { gareA: "Dambach-la-Ville", gareB: "Eichhoffen", longueur: 6.9, type: "classique", vitesse_max: 80, electrification: "diesel", signalisation: "KVB" },
  { gareA: "Eichhoffen", gareB: "Gertwiller", longueur: 3.9, type: "classique", vitesse_max: 80, electrification: "diesel", signalisation: "KVB" },
  { gareA: "Gertwiller", gareB: "Obernai", longueur: 5.9, type: "classique", vitesse_max: 80, electrification: "diesel", signalisation: "KVB" },
  { gareA: "Obernai", gareB: "Bischoffsheim", longueur: 2.9, type: "classique", vitesse_max: 80, electrification: "diesel", signalisation: "KVB" },
  { gareA: "Bischoffsheim", gareB: "Rosheim", longueur: 2.2, type: "classique", vitesse_max: 80, electrification: "diesel", signalisation: "KVB" },
  { gareA: "Rosheim", gareB: "Molsheim", longueur: 3.6, type: "classique", vitesse_max: 80, electrification: "diesel", signalisation: "KVB" },
  { gareA: "Scherwiller", gareB: "Dambach-la-Ville", longueur: 3.9, type: "classique", vitesse_max: 80, electrification: "diesel", signalisation: "KVB" },
  { gareA: "Vendenheim", gareB: "Mundolsheim", longueur: 2.4, type: "classique", vitesse_max: 140, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "Mundolsheim", gareB: "_AiguillageStrasNord", longueur: 5.5, type: "classique", vitesse_max: 140, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "_AiguillageStrasNord", gareB: "Strasbourg", longueur: 2, type: "classique", vitesse_max: 140, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "_AiguillageStrasNord", gareB: "_courbeStrasSud", longueur: 4.3, type: "classique", vitesse_max: 140, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "_AiguillageStrasNord", gareB: "_VendenheimEvitement", longueur: 6.5, type: "classique", vitesse_max: 160, electrification: "25kV CA", signalisation: "ETCS" },
  { gareA: "_VendenheimEvitement", gareB: "_SéparationNordStras", longueur: 1.4, type: "classique", vitesse_max: 160, electrification: "25kV CA", signalisation: "ETCS" }
];